services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    env_file:
      - ./back/.env
    volumes:
      - ./back:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: fastapi_password
      POSTGRES_DB: fastapi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6380:6379"

  celery-beat:
    image: cybercheck-backend  # Utilisez la même image que le backend
    container_name: celery-beat
    command: celery -A celery_app beat --loglevel=info
    volumes:
      - ./back:/app
    depends_on:
      - redis

  celery-worker:
    image: cybercheck-backend  # Utilisez la même image que le backend
    container_name: celery-worker
    command: celery -A celery_app worker --loglevel=info
    volumes:
      - ./back:/app
    depends_on:
      - redis

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: vue-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
    command: npm run dev

volumes:
  postgres_data: